policies:
  - name: Update Go version
    id: local
    config:
      - "updatecli.d"
    values:
      - values.yaml
  - name: Update golangci-lint
    id: golangci-lint
    policy: ghcr.io/updatecli/policies/golangci-lint/githubaction:0.8.1@sha256:7fb34ae17a84641f02c3ff2aa0f8156a7108f32f21282b0070b8883c86ba6e67
